export const PROJECTS = [
  
  {
    id: 'study-buddy',
    title: 'Study Buddy',
    year: '2024',
    tags: ['DSA', 'Full-Stack', 'Python'],
    color: '#EDE5D8',
    description: 'Intelligent study-group finder that auto-matches students by subject, language, and GPA. Dynamic reshuffling with hash maps, queues, and linked lists keeps groups balanced as membership changes.',
    tech: 'Python · React · Flask · DSA',
    link: 'https://github.com/yoginiaishwaryaa',
    emoji: '📚',
  },
  {
    id: 'thermal-fruit',
    title: 'Thermal Fruit Dataset',
    year: '2025',
    tags: ['Research', 'ML', 'Dataset'],
    color: '#fad8d8',
    description: 'Captured and annotated 3,200+ thermal images of fruits — the first public thermal fruit dataset. Published in Elsevier Data in Brief (2026). Powers a thermal-image classification pipeline using preprocessing and augmentation.',
    tech: 'Python · PyTorch · Thermal Imaging · Research',
    link: 'https://doi.org/10.1016/j.dib.2026.112545',
    emoji: '🌡️',
  },
  {
    id: 'handes-control',
    title: 'HandesControl',
    year: '2025',
    tags: ['CV', 'Python', 'HCI'],
    color: '#DCF0E8',
    description: 'Control your mouse with hand gestures via webcam. Built with MediaPipe + OpenCV + PyAutoGUI. Index-finger movement drives the cursor; pinch gestures trigger clicks. First ML project.',
    tech: 'Python · MediaPipe · OpenCV · PyAutoGUI',
    link: 'https://github.com/yoginiaishwaryaa/Handes-Control',
    emoji: '✋',
  },
  {
    id: 'handheld-console',
    title: 'Handheld Game Console',
    year: '2025',
    tags: ['Embedded', 'Hardware', 'C'],
    color: '#D4E8D8',
    description: 'A bare-metal handheld console on STM32F401CCU6 designed for users requiring simplified controls — including people with cognitive challenges. ADC joystick, EXTI buttons, I2C LCD, SysTick scheduling. Fully playable.',
    tech: 'STM32 · Bare-Metal C · ADC · I2C · SysTick',
    link: 'https://github.com/yoginiaishwaryaa/Handheld-Game-Console',
    emoji: '🕹️',
  },
  {
    id: 'ecg-detection',
    title: 'ECG Arrhythmia Detector',
    year: '2025',
    tags: ['ML', 'Edge AI', 'Python'],
    color: '#F2E8E0',
    description: 'Edge-deployable arrhythmia detection on MIT-BIH ECG signals. 1D-CNN + GRU + fuzzy-logic post-processing achieves 95.2% accuracy within strict memory and latency budgets of real embedded devices.',
    tech: 'Python · TensorFlow · 1D-CNN · GRU · Fuzzy Logic',
    link: 'https://github.com/yoginiaishwaryaa',
    emoji: '💓',
  },
  {
    id: 'shelly',
    title: 'Shelly',
    year: '2025',
    tags: ['Python', 'Node.js', 'Tailwind CSS'],
    color: '#f2efe0',
    description: 'AI-powered shopping assistant delivering personalized product recommendations, sustainability-driven insights, and mascot customization features that promote engagement and environmentally conscious decision-making.',
    tech: 'Python · Node.js · Tailwind CSS · OpenAI API',
    link: 'https://github.com/Santhosh292K/Shelly',
    emoji: '🛍️',
  },
  {
    id: 'script-match',
    title: 'ScriptMatch',
    year: '2026',
    tags: ['AI', 'Azure', 'Full-Stack'],
    color: '#E0DCF0',
    description: 'Serverless Azure platform that recommends movies by transcribing and analysing actual dialogue — not just genre tags. Uses Azure AI Video Indexer, Event Grid, Logic Apps, and AI Search to build a semantic content graph from what characters say.',
    tech: 'Azure · Python · AI Video Indexer · Logic Apps',
    link: 'https://github.com/yoginiaishwaryaa/script-match',
    emoji: '🎬',
  },
  {
    id: 'multiplayer-card',
    title: 'Multiplayer Card Clash',
    year: '2026',
    tags: ['Full-Stack', 'Networking', 'Real-time'],
    color: '#D8EAF5',
    description: 'Real-time networked card game on a client-server architecture. Python multi-threaded backend broadcasts game state to all clients; TypeScript/CSS frontend renders a live, synchronised board.',
    tech: 'Python · TypeScript · Sockets · Multi-threading',
    link: 'https://github.com/yoginiaishwaryaa/Multiplayer-Card-Clash',
    emoji: '🃏',
  },
  {
    id: 'Secure-Quiz Platform',
    title: 'Secure-Quiz Platform',
    year: '2026',
    tags: ['Full-Stack', 'Security', 'Gamification'],
    color: '#f5d8e7',
    description: 'Secure Quiz Platform, a role-based web quiz application that focuses on secure authentication, encrypted quiz data storage, and fair, gamified gameplay.',
    tech: 'Python · Hybrid Authentication · NIST SP 800-63-2 · React',
    link: 'https://github.com/yoginiaishwaryaa/Secure-Quiz-Platform',
    emoji: '❓',
  },
]

export const PUBLICATIONS = [
  
  {
    id: 'figshare-2025',
    title: 'Thermal Fruit Image Dataset (Raw)',
    journal: 'Figshare Repository',
    year: '2025',
    doi: 'https://doi.org/10.6084/m9.figshare.30783827',
    color: '#E0DCF0',
    description: 'Open-access figshare repository hosting the raw thermal imaging data, annotations, and Arduino sensor calibration scripts that underpin the published paper.',
  },
  
  {
    id: 'dib-2026',
    title: 'Thermal Fruit Image Dataset',
    journal: 'Elsevier — Data in Brief',
    year: '2026',
    doi: 'https://doi.org/10.1016/j.dib.2026.112545',
    color: '#D4E8D8',
    description: 'A curated dataset of 3,200+ thermal images of fruits and vegetables, captured under controlled conditions. First-of-its-kind public thermal fruit dataset enabling research in thermal classification and food quality inspection.',
  },
]

export const SKILLS = [
  { label: 'Python', category: 'Languages' },
  { label: 'C / C++', category: 'Languages' },
  { label: 'Java', category: 'Languages' },
  { label: 'JavaScript', category: 'Languages' },
  { label: 'SQL', category: 'Languages' },
  { label: 'React', category: 'Web' },
  { label: 'Node.js', category: 'Web' },
  { label: 'Flask', category: 'Web' },
  { label: 'HTML5', category: 'Web' },
  { label: 'CSS3', category: 'Web' },
  { label: 'STM32 / Embedded', category: 'Hardware' },
  { label: 'Arduino', category: 'Hardware' },
  { label: 'Raspberry Pi', category: 'Hardware' },
  { label: 'Bare-Metal C', category: 'Hardware' },
  { label: 'TensorFlow', category: 'ML' },
  { label: 'PyTorch', category: 'ML' },
  { label: 'MediaPipe', category: 'ML' },
  { label: 'OpenCV', category: 'ML' },
  { label: 'NumPy', category: 'ML' },
  { label: 'Azure', category: 'Cloud' },
  { label: 'AWS', category: 'Cloud' },
  { label: 'GCP', category: 'Cloud' },
  { label: 'Docker', category: 'Cloud' },
  { label: 'GitHub Actions', category: 'Cloud' },
  { label: 'Figma', category: 'Design' },
  { label: 'Product Thinking', category: 'Design' },
  { label: 'User Research', category: 'Design' },
]

export const CONTACT = {
  email: 'yoginianithakumar@gmail.com',
  github: 'https://github.com/yoginiaishwaryaa',
  phone: '9487947472',
}
